<?php

/**
 * Conta
 * 
 * This class has been auto-generated by the Code Igniter Generator Framework
 * 
 */
class Planos_model extends CI_Model
{
	public $table = "planos";

	public function __construct()
	{
		parent::__construct();
	}

	public function getPlanos() {
		return $this->db->query("SELECT id, nome_plano, telefone_plano, email_plano, status, createdAt, updatedAt
								 FROM planos
								 ORDER BY id DESC")
						->result();

	}
	
}
