{?php

/**
 * Conta
 * 
 * This class has been auto-generated by the Code Igniter Generator Framework
 * 
 */
class <?php echo ucfirst(camelCase($modulo)); ?>_model extends CI_Model
{
	public $table = "<?php echo strtolower($modulo)?>";

	public function __construct()
	{
		parent::__construct();
	}
	
}
